# -*- coding: utf-8 -*-
"""SemanticShit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GK44bHn5Ss6A1WlbAFPYCqO34-3lqDw
"""

from google.colab import files

files.upload()

### we import required libraries
try:
  import pixellib
  from pixellib.instance import instance_segmentation
  import cv2 as cv## for computer vision
  import logging ## to display errors
  import tensorflow as tf
except Exception as e:
  logging.critical('{}'.format(e))

path = tf.keras.utils.get_file(
    "Mask_RCNN",
    "https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5",
    extract=True)

### setting up the model
##(https://www.tensorflow.org/datasets/catalog/coco)

segmentation_model = instance_segmentation() ## intialize the function
segmentation_model.load_model(path) ## get the mask RCNN coco dataset

#### testing out the model with randome images

img = cv.imread('/content/Traffic.jpg') ### loading the images
res = segmentation_model.segmentFrame(img, show_bboxes=True) ### loading the module

from google.colab.patches import cv2_imshow
image = res[1]
cv2_imshow(image)

### loading video feed from cam
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Apply instance segmentation
    res = segmentation_model.segmentFrame(frame, show_bboxes=True)
    image = res[1]
    
    cv2.imshow('Instance Segmentation', image)
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()